baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo-Tailwind'

# ignore Templates/.md
ignoreFiles = [ '模板\.md']



[author]
name = "Junker"
avatar = "https://s2.loli.net/2022/07/09/wY63xOJybHNfGcT.jpg"
banner = ""
bio = "Tritype-147"


#Menu Settings

[menu]
    [[menu.main]]
        url = "/poem"
        name = "Poem"
        weight = 1
    [[menu.main]]
        url = "/life"
        name = "Life"
        weight = 2
    [[menu.main]]
        url = "/tech"
        name = "Tech"
        weight = 3
    [[menu.main]]
        url = "/about"
        name = "About"
        weight = 4

