baseURL = 'https://junklog.vercel.app/'
languageCode = 'en-us'
title = 'Hugo-Tailwind'

# ignore Templates/.md
ignoreFiles = [ '模板\.md']



[author]
name = "雅佚"
avatar = "https://s2.loli.net/2022/07/09/wY63xOJybHNfGcT.jpg"
banner = ""
bio = "Tritype-147, 不必訝異, 無須歡喜"


#Menu Settings

[menu]
    [[menu.main]]
        pageref = "/poem/"
        url = "/poem/"
        name = "Poem"
        title = "梅花落满了南山"
        weight = 1
    [[menu.main]]
        pageref = "/life/"
        url = "/life/"
        name = "Life"
        title = "生命与生活无关"
        weight = 2
    [[menu.main]]
        pageref = "/tech/"
        url = "/tech/"
        name = "Tech"
        title = "当美丽的故事来得太晚"
        weight = 3
    [[menu.main]]
        pageref = "/about/"
        url = "/about/"
        name = "About"
        title = "去码头整点薯条"
        weight = 4

